gridWorkingDir:		  workingdir
gridOutputDir:		  outputdir_17o_muon_calo
aliROOTVersion:		  v5-09-22-1
aliPhysicsVersion:	v5-09-22-01-1
gridDataDir:		    /alice/data/2017/LHC17o
dataPattern:		    /muon_calo_pass1/*/AliESDs.root
runPrefix:          000
runNumber:          [281961]
# https://alimonitor.cern.ch/configuration/index.jsp?partition=LHC17o&pass=-1&s=»&raw_run=&filling_scheme=&filling_config=&fillno=&energy=&intensity_per_bunch=&mu=&interacting_bunches=&noninteracting_bunches_beam_1=&noninteracting_bunches_beam_2=&interaction_trigger=&rate=&beam_empty_trigger=&empty_empty_trigger=&muon_trigger=&high_multiplicity_trigger=&emcal_trigger=&calibration_trigger=&quality=&muon_quality=1&physics_selection_status=&comment=&field=&det_aco=&det_ad0=&det_emc=1&det_fmd=&det_hlt=&det_hmp=&det_mch=1&det_mtr=1&det_phs=&det_pmd=&det_spd=1&det_sdd=&det_ssd=&det_tof=&det_tpc=&det_trd=&det_t00=&det_v00=&det_zdc=&hlt_mode=&changedon=
# emcalCorrection:  emcal_correction.yaml
emcalCorrection:
splitMaxInputFileNumber:  100
storedJetMinPtRaw: 10
